# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
revisionHistoryLimit: 5
image:
  repository: sushantsahu/kube-node-101-run
  tag: 1.2.0
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 800m
      memory: 500Mi
  #readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 3
    periodSeconds: 5
  #livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  livenessProbe:
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 40
    periodSeconds: 10  
service:
  name: kube-101-service
  type: NodePort
  servicePort: 3000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
